name: Lint and Test

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.11

    - name: Install module and dependencies
      run: python -m pip install . && python -m pip install .[dev]

    - name: Run linters
      run: python -m ruff cobp && python -m mypy cobp

    - name: Run tests
      run: python -m pytest tests